services:
  postgres-testing:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  redis-testing:
    image: redis
    ports:
      - "6379:6379"
